"""removed sv id from 8d model

Revision ID: 1ffa7e30f6ed
Revises: 951b3cee11c0
Create Date: 2025-07-30 12:48:32.022706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ffa7e30f6ed'
down_revision = '951b3cee11c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostics_8d', schema=None) as batch_op:
        batch_op.drop_column('system_version_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostics_8d', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_version_id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
