"""closed in 8d is not nullable

Revision ID: 6d062c765616
Revises: c5be8c677fc2
Create Date: 2025-08-04 12:36:51.938503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d062c765616'
down_revision = 'c5be8c677fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostics_8d', schema=None) as batch_op:
        batch_op.alter_column('closed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostics_8d', schema=None) as batch_op:
        batch_op.alter_column('closed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
