"""added relationships

Revision ID: 879ffb83e014
Revises: 9903fc704529
Create Date: 2025-08-01 10:27:49.412033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879ffb83e014'
down_revision = '9903fc704529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostics_8d', schema=None) as batch_op:
        batch_op.alter_column('root_cause_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_product_product', ['product'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('uq_product_product', type_='unique')

    with op.batch_alter_table('diagnostics_8d', schema=None) as batch_op:
        batch_op.alter_column('root_cause_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
