"""moved system version to diagnostic

Revision ID: 951b3cee11c0
Revises: c36a7b8bee3a
Create Date: 2025-07-30 11:58:34.680757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951b3cee11c0'
down_revision = 'c36a7b8bee3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostics_8d', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_sn', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('to_sn', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('from_version', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('to_version', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('from_supply_date', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('to_supply_date', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('from_sw', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('to_sw', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostics_8d', schema=None) as batch_op:
        batch_op.drop_column('to_sw')
        batch_op.drop_column('from_sw')
        batch_op.drop_column('to_supply_date')
        batch_op.drop_column('from_supply_date')
        batch_op.drop_column('to_version')
        batch_op.drop_column('from_version')
        batch_op.drop_column('to_sn')
        batch_op.drop_column('from_sn')

    # ### end Alembic commands ###
