"""init migr

Revision ID: 96441ffefa17
Revises: 
Create Date: 2025-08-25 11:16:51.401593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96441ffefa17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue'),
    sa.UniqueConstraint('issue', name='uq_issue_issue')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('help_text_link', sa.Text(), nullable=True),
    sa.Column('help_image_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question', name='uq_question_question')
    )
    op.create_table('root_cause',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system'),
    sa.UniqueConstraint('system', name='uq_system_system')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.Text(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product'),
    sa.UniqueConstraint('product', name='uq_product_product')
    )
    op.create_table('diagnostics_8d',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('from_sn', sa.VARCHAR(), nullable=True),
    sa.Column('to_sn', sa.VARCHAR(), nullable=True),
    sa.Column('from_version', sa.VARCHAR(), nullable=True),
    sa.Column('to_version', sa.VARCHAR(), nullable=True),
    sa.Column('from_supply_date', sa.VARCHAR(), nullable=True),
    sa.Column('to_supply_date', sa.VARCHAR(), nullable=True),
    sa.Column('from_sw', sa.VARCHAR(), nullable=True),
    sa.Column('to_sw', sa.VARCHAR(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('temporary_fix', sa.Text(), nullable=True),
    sa.Column('root_cause_id', sa.Integer(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('preventative_action', sa.Text(), nullable=True),
    sa.Column('verified_fix', sa.Boolean(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('link_8d', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], name='fk_diagnostics_8d_issue_id'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='fk_diagnostics_8d_product_id'),
    sa.ForeignKeyConstraint(['root_cause_id'], ['root_cause.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part', sa.VARCHAR(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part'),
    sa.UniqueConstraint('part', name='uq_part_part')
    )
    op.create_table('product_question',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'question_id')
    )
    op.create_table('diagnostics_8d_question',
    sa.Column('diagnostics_8d_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diagnostics_8d_id'], ['diagnostics_8d.id'], name='fk_diagnostics_8d_id_diagnostics_8d_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='fk_question_id_question_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('diagnostics_8d_id', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnostics_8d_question')
    op.drop_table('product_question')
    op.drop_table('part')
    op.drop_table('diagnostics_8d')
    op.drop_table('product')
    op.drop_table('system')
    op.drop_table('root_cause')
    op.drop_table('question')
    op.drop_table('issue')
    # ### end Alembic commands ###
