"""initial migration

Revision ID: 9903fc704529
Revises: 
Create Date: 2025-07-31 11:33:57.399363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9903fc704529'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('help_text_link', sa.Text(), nullable=True),
    sa.Column('help_image_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product'),
    sa.UniqueConstraint('product', name='uq_product_product')
    )
    op.create_table('root_cause',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnostics_8d',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('from_sn', sa.VARCHAR(), nullable=True),
    sa.Column('to_sn', sa.VARCHAR(), nullable=True),
    sa.Column('from_version', sa.VARCHAR(), nullable=True),
    sa.Column('to_version', sa.VARCHAR(), nullable=True),
    sa.Column('from_supply_date', sa.VARCHAR(), nullable=True),
    sa.Column('to_supply_date', sa.VARCHAR(), nullable=True),
    sa.Column('from_sw', sa.VARCHAR(), nullable=True),
    sa.Column('to_sw', sa.VARCHAR(), nullable=True),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('temporary_fix', sa.Text(), nullable=True),
    sa.Column('root_cause_id', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('preventative_action', sa.Text(), nullable=True),
    sa.Column('verified_fix', sa.Text(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.Column('link_8d', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='fk_diagnostics_8d_product_id'),
    sa.ForeignKeyConstraint(['root_cause_id'], ['root_cause.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('root_cause_question',
    sa.Column('root_cause_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['Question.id'], ),
    sa.ForeignKeyConstraint(['root_cause_id'], ['root_cause.id'], ),
    sa.PrimaryKeyConstraint('root_cause_id', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('root_cause_question')
    op.drop_table('diagnostics_8d')
    op.drop_table('root_cause')
    op.drop_table('product')
    op.drop_table('Question')
    # ### end Alembic commands ###
