"""new initial migration

Revision ID: bf1138e8d9ee
Revises: dc8cd5ead332
Create Date: 2025-07-28 14:17:45.495943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1138e8d9ee'
down_revision = 'dc8cd5ead332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_sn', sa.VARCHAR(), nullable=True),
    sa.Column('to_sn', sa.VARCHAR(), nullable=True),
    sa.Column('from_version', sa.VARCHAR(), nullable=True),
    sa.Column('to_version', sa.VARCHAR(), nullable=True),
    sa.Column('from_supply_date', sa.VARCHAR(), nullable=True),
    sa.Column('to_supply_date', sa.VARCHAR(), nullable=True),
    sa.Column('from_sw', sa.VARCHAR(), nullable=True),
    sa.Column('to_sw', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('root_cause_question',
    sa.Column('root_cause_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['Question.id'], ),
    sa.ForeignKeyConstraint(['root_cause_id'], ['root_cause.id'], ),
    sa.PrimaryKeyConstraint('root_cause_id', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('root_cause_question')
    op.drop_table('system_version')
    # ### end Alembic commands ###
