"""moved system version to diagnostic

Revision ID: c36a7b8bee3a
Revises: f556ac2a9e0c
Create Date: 2025-07-30 11:58:05.158709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c36a7b8bee3a'
down_revision = 'f556ac2a9e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_version',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('from_sn', sa.VARCHAR(), nullable=True),
    sa.Column('to_sn', sa.VARCHAR(), nullable=True),
    sa.Column('from_version', sa.VARCHAR(), nullable=True),
    sa.Column('to_version', sa.VARCHAR(), nullable=True),
    sa.Column('from_supply_date', sa.VARCHAR(), nullable=True),
    sa.Column('to_supply_date', sa.VARCHAR(), nullable=True),
    sa.Column('from_sw', sa.VARCHAR(), nullable=True),
    sa.Column('to_sw', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
