"""second migration

Revision ID: c5be8c677fc2
Revises: f9273d802e62
Create Date: 2025-08-04 12:27:07.405302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5be8c677fc2'
down_revision = 'f9273d802e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_question',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'question_id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_product_product', ['product'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('uq_product_product', type_='unique')

    op.drop_table('product_question')
    # ### end Alembic commands ###
