"""product uniqueness set to True

Revision ID: f556ac2a9e0c
Revises: 0c5b081ab618
Create Date: 2025-07-30 11:28:53.262804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f556ac2a9e0c'
down_revision = '0c5b081ab618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_product_product', ['product'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('uq_product_product', type_='unique')

    # ### end Alembic commands ###
